name: spiphoto_app
description: "A SPIPHOTO project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dépendances du SDK Flutter
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  html: ^0.15.4
  url_launcher: ^6.2.2
  
# Dépendances spécifiques dave
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^2.0.0
flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icons/mon_logo1.png"

# Paramètres spécifiques à l'application
flutter:
  uses-material-design: true
  assets:
    - android/app/src/main/res/mipmap-hdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png