name: spiphoto_app
description: "A SPIPHOTO project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

# Dépendances du SDK Flutter
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  #provider: ^6.0.0
  #flutter_math_fork: ^0.5.0

# Dépendances spécifiques dave
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^2.0.0


# Paramètres spécifiques à l'application
flutter:
  uses-material-design: true