name: spiphoto_app
description: "A SPIPHOTO project."
publish_to: 'none'
version: 1.5.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# ── Dépendances ───────────────────────────────────────────────────────────────
dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  html: ^0.15.4
  url_launcher: ^6.3.2
  easy_image_viewer: ^1.4.1
  extended_image: ^10.0.1
  share_plus: ^11.0.0

# ── Dépendances de développement ─────────────────────────────────────────────
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/mon_logo1.png"

# ── Flutter ───────────────────────────────────────────────────────────────────
flutter:
  uses-material-design: true

  assets:
    - android/app/src/main/res/mipmap-hdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xhdpi/rounded_launcher.png
    - android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
    - assets/icons/mon_logo1.png
    - assets/ca/lets-encrypt-r3.pem